[build]
target = "index.html"
dist = "dist"

[watch]
watch = ["src", "styles", "index.html"]

[serve]
address = "127.0.0.1"
port = 8080
open = false

[[hooks]]
stage = "build"
command = "sh"
command_arguments = ["-c", "echo 'Setting environment variables...'"]

[env]
API_HOST = "http://127.0.0.1:3000"
